name: PHP Lints

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

jobs:
  lint-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Setup npm cache
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ env.cache-name }}-
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

        # TODO: Only install @wordpress/env
      - name: Install dependencies
        run: npm ci
        env:
          CI: true
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer:v1, cs2pr

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup Composer cache
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
            ${{ runner.os }}-

      - name: Validate composer.json
        run: composer --no-interaction --no-check-all validate

        # TODO: Use `npm run wp-env run composer` once using Composer 2.
      - name: Install dependencies
        run: composer install --prefer-dist --no-suggest --no-progress --no-interaction

      - name: Detect coding standard violations (PHPCS)
        run: |
          composer lint -- --version
          composer lint -- -v

      - name: Static Analysis (PHPStan)
        run: composer phpstan -- --error-format=checkstyle | cs2pr

      - name: Static Analysis (PHPMD)
        run: composer phpmd

      - name: Normalize composer.json
        run: composer composer-normalize --no-interaction -- --dry-run
